
data:
  dataset: thor
  num_points: 4096
  kwargs:
    canonical_view: true
model:
  encoder_kwargs:
    use_conv: false
    pos_start_octave: -5
  decoder: lightfield
  decoder_kwargs:
    pos_start_octave: -5
training:
  num_workers: 6
  batch_size: 224
  model_selection_metric: psnr
  model_selection_mode: maximize
  print_every: 10
  visualize_every: 5000
  validate_every: 5000
  checkpoint_every: 1000
  backup_every: 100000
  max_it: 4000000
  decay_it: 4000000
  lr_warmup: 2500
